#! /bin/sh

grep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &

emacs --daemon &pgrep -x emacs >/dev/null || emacs --daemon &

killall polybar 2>/dev/null 
polybar -c "/home/kishor/.config/polybar/config.ini" mybar &
killall nm-applet 2>/dev/null
nm-applet &

killall picom 2>/dev/null
picom --vsync &
feh --bg-fill "/home/kishor/.config/bspwm/moon.jpg" &
urxvtd -q -o -f &
$HOME/.config/bspwm/pen-setup.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10



bspc config border_width         2
bspc config window_gap           8
bspc config normal_border_color   "#475B63"
bspc config active_border_color   "#BACDB0"
bspc config focused_border_color  "#BACDB0" 
bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^2' focus=off
bspc rule -a obsidian desktop='^10' focus=off state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a EzPlay state=floating
bspc rule -a AtomLog state=floating
