# add new lines between prompts
add_newline = true

format="""
$directory\
$git_branch\
$git_status\
$line_break\
$character\
"""

[directory]
style = "bold blue"
truncate_to_repo = true

[git_branch]
style = "bold purple"

